# Task 2 - Guided Diamonds Project
Author: [Adrian Vega](https://github.com/adriacv17) <br >Respository: [datafun-06-projects](https://github.com/adriacv17/datafun-06-projects) <br> Data: 09/28/2023

## Section 1-Load: Get the file, store it in your repo, and load it into a DataFrame.

In [27]:
import pandas as pd # import pandas library
import numpy as np # import numpy library

diamondsdf = pd.read_csv('diamonds.csv', index_col=0) # Create a DataFrame from csv file

# renaming other columns with small changes for better understanding measures
diamondsdf.columns = ['carat', 'cut', 'color', 'clarity', 'depth(%)', 'table(%)', 'price(USD)', 'x(mm)', 'y(mm)', 'z(mm)'] 

diamondsdf # call DataFrame

,carat,cut,color,clarity,depth(%),table(%),price(USD),x(mm),y(mm),z(mm)
1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

## Section 2-View: Display the first 7 rows and the last 7 rows.

In [28]:
diamondsdf.head(7) #display first 7 rows

,carat,cut,color,clarity,depth(%),table(%),price(USD),x(mm),y(mm),z(mm)
1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
6,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48
7,0.24,Very Good,I,VVS1,62.3,57.0,336,3.95,3.98,2.47

In [29]:
diamondsdf.tail(7) #display last 7 rows

,carat,cut,color,clarity,depth(%),table(%),price(USD),x(mm),y(mm),z(mm)
53934,0.70,Very Good,E,VS2,61.2,59.0,2757,5.69,5.72,3.49
53935,0.72,Premium,D,SI1,62.7,59.0,2757,5.69,5.73,3.58
53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

## Section 3-Describe: Use the DataFrame describe() function to calculate basic descriptive statistics for all numeric columns.

## Section 4-Series: Use the Series method describe() to calculate the descriptive stats for all category/text columns.

## Section 5-Unique: Use the Series method unique() to get unique category values.

## Section 6-Histograms: Use the DataFrame's hist() function to create a histogram for each numerical column.